### ISSUE TITLE
nano.db is undefined

### ISSUE THREAD

**Issue by hughrawlinson** [cloudant/nodejs-cloudant#115]
On cloudant.js on [line 128](https://github.com/cloudant/nodejs-cloudant/blob/master/cloudant.js#L128), you try to assign `use` to `nano.db` which is undefined.

For reference, [here](https://gist.github.com/hughrawlinson/8e58de9272c41cc86053) is my code that reproduces the issue.

```
> jams-server@1.0.7 start /home/hugh/Development/trajectorialPlaylisting/storageServer
> node server.js

/home/hugh/Development/trajectorialPlaylisting/storageServer/node_modules/cloudant/cloudant.js:128
  nano.use = nano.db.use = use;
                         ^

TypeError: Cannot set property 'use' of undefined
    at Cloudant (/home/hugh/Development/trajectorialPlaylisting/storageServer/node_modules/cloudant/cloudant.js:128:26)
    at /home/hugh/Development/trajectorialPlaylisting/storageServer/lib/dbs/cloudant.js:6:37
    at Object.<anonymous> (/home/hugh/Development/trajectorialPlaylisting/storageServer/lib/dbs/cloudant.js:51:3)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /home/hugh/Development/trajectorialPlaylisting/storageServer/server.js:24:10

npm ERR! Linux 4.2.0-19-generic
npm ERR! argv "/home/hugh/.nvm/versions/node/v5.1.0/bin/node" "/home/hugh/.nvm/versions/node/v5.1.0/bin/npm" "start"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! jams-server@1.0.7 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jams-server@1.0.7 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jams-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls jams-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hugh/Development/trajectorialPlaylisting/storageServer/npm-debug.log
```

FAO: @ukmadlz

**Comment by glynnbird** [comment]
Is is possible to post the code you used to instantiate the Cloudant object? It seems to work for me:

```js
var Cloudant = require('cloudant');
// Initialize the library with my account.
var cloudant = Cloudant({ url: "https://reader.cloudant.com"});


var mydb = cloudant.db.use("guitars");
var query = {
        "selector": {
            "brand": "Fender"
        }
};

mydb.find(query, function(err, doc) {
    if(err) {
        console.log("ERROR!",err);        
    } else {
        console.log("SUCCESS", doc);
    }
});
```

**Comment by willholley** [comment]
possible duplicate of https://github.com/cloudant/nodejs-cloudant/issues/96

**Comment by hughrawlinson** [comment]
I didn't get a chance to check my code, and I'm fairly sure I've lost by now. Sounds like a duplicate of #96, so I'm gonna close this issue :)
