### ISSUE TITLE
specifying database in url fails

### ISSUE THREAD

**Issue by b-admike** [cloudant/nodejs-cloudant#181]
Hi, `loopback-connector-cloudant` uses this module to talk to cloudant, and our users sometimes put the database name in the `url` field and run into the following issue:
```
| => node
> var Cloudant = require('cloudant')
undefined
> var cloudant = Cloudant("https://MYUSERNAME:MYPASSWORD@MYACCOUNT.cloudant.com");
undefined
> var cloudant2 = Cloudant("https://MYUSERNAME:MYPASSWORD@MYACCOUNT.cloudant.comi/foobar");
TypeError: Cannot set property 'use' of undefined
    at Cloudant (/Users/badmike/mysql65repo/lbconcloudant18/node_modules/cloudant/cloudant.js:173:26)
    at repl:1:17
    at REPLServer.defaultEval (repl.js:272:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:441:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:212:10)
    at REPLServer.Interface._line (readline.js:551:8)
```
It looks like this is supported in nano [here](https://github.com/apache/couchdb-nano#configuration). Would it be supported here as well or are we expected to continue usage like [so](https://github.com/cloudant/nodejs-cloudant/issues/96#issuecomment-178047190)?

**Comment by smithsz** [comment]
Sorry for the delayed response. This is not supported since under the hood we're intercepting `nano.use` calls in order to plug in our own Cloudant extensions. We also add a few nano top-level functions too. Please initialise the client using your account URL (see below). Thanks.

```
var cloudant = Cloudant("https://MYUSERNAME:MYPASSWORD@MYACCOUNT.cloudant.com");
```
