### ISSUE TITLE
Crash detected in clientutils.js:111 

### ISSUE THREAD

**Issue by devanshah2** [cloudant/nodejs-cloudant#299]
Please include the following information in your ticket.

- Cloudant (nodejs-cloudant) version(s) that are affected by this issue: **2.1.0**
- Node version: **8.10.0**

- A small code sample that demonstrates the issue.

It is hard to provide a code sample that is able to reproduce this issues, as this is intermittent/race condition. But at a minimum need to make sure it does not crash the running script https://github.com/cloudant/nodejs-cloudant/blob/master/lib/clientutils.js#L111

We are faced with exception:

`
/usr/app/node_modules/async/dist/async.js:985
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /usr/app/node_modules/async/dist/async.js:985:32
    at next (/usr/app/node_modules/async/dist/async.js:3589:25)
    at /usr/app/node_modules/async/dist/async.js:3363:26
    at Object.processState (/usr/app/node_modules/@cloudant/cloudant/lib/clientutils.js:111:7)
    at /usr/app/node_modules/@cloudant/cloudant/lib/client.js:342:17
    at /usr/app/node_modules/async/dist/async.js:484:16
    at replenish (/usr/app/node_modules/async/dist/async.js:1025:25)
    at iterateeCallback (/usr/app/node_modules/async/dist/async.js:1015:17)
    at /usr/app/node_modules/async/dist/async.js:988:16
    at updateState (/usr/app/node_modules/@cloudant/cloudant/lib/clientutils.js:53:3)
    at /usr/app/node_modules/@cloudant/cloudant/lib/clientutils.js:129:11
    at RetryPlugin.onResponse (/usr/app/node_modules/@cloudant/cloudant/plugins/retry.js:48:5)
    at /usr/app/node_modules/@cloudant/cloudant/lib/clientutils.js:128:25
    at /usr/app/node_modules/async/dist/async.js:3205:16
    at replenish (/usr/app/node_modules/async/dist/async.js:1030:17)
    at /usr/app/node_modules/async/dist/async.js:1034:9
`

**Comment by tomblench** [comment]
@devanshah2 I appreciate that you said "It is hard to provide a code sample" but can you provide us more information about what you are doing which causes this exception to be thrown?

**Comment by devanshah2** [comment]
@tomblench We are running over lets say 60+ concurrent GET (by view) calls using this module to hit cloudant or couchdb.

**Comment by tomblench** [comment]
OK, that sounds like it shouldn't be too difficult for you to provide a sample to help us reproduce the issue - I'm guessing it should just be a few lines of JS. Are you using `async` or similar to make these concurrent GETs?

**Comment by devanshah2** [comment]
@tomblench We have tried to create a small scripts that uses `async` to run multiple parallel GETs and it was not able to reproduce. I tried to hit it with close to 1000 and no luck. Will see what else can be done.

**Comment by smithsz** [comment]
I'm struggling to reproduce this. I've had a read through the code but it's not clear how this happens.

This is a bit of a hack but might resolve the problem - https://github.com/cloudant/nodejs-cloudant/compare/fix-multiple-callback-execution.

Let me know what you think.

**Comment by devanshah2** [comment]
@smithsz Looking at the change. This does look like it can fix the issue. Any change you can create a package and send it my way, I can toss it into our service where the issue happens and verify it.

**Comment by smithsz** [comment]
@devanshah2 Sorry for the delay. Please try the `@cloudant/cloudant@2.2.0-SNAPSHOT.64` snapshot release on NPM. Let me know how you get on. Thanks.

**Comment by devanshah2** [comment]
@smithsz No Worries. Thanks. Will give this a try and let you know.

**Comment by devanshah2** [comment]
@smithsz We have it tried it out and we do not face the crash anymore, looks like this is fixed. Any idea when this will make it in to the next release.

**Comment by ricellis** [comment]
This was already released in [2.2.0](https://github.com/cloudant/nodejs-cloudant/releases/tag/2.2.0).
