### ISSUE TITLE
Compatibility with Node 0.12 and Proxy problem

### ISSUE THREAD

**Issue by spifd** [cloudant/nodejs-cloudant#38]
Hi,

I'm having some problem due to proxy configuration when running on Node.js 0.12.2 (btw not sure it is yet supported as npm warns me against `follow` dependency requiring 0.8x or 0.10.x).

Actually, I simply use the basic example from the tutorial to check connection and list databases. I've just added proxy configuration to it. The sample runs fine on 0.10.8, connecting through our proxy, but fails to connect on 0.12.2 with the following error:

```
http_client.js:73
    throw new TypeError('Request path contains unescaped characters.');
          ^
TypeError: Request path contains unescaped characters.
    at new ClientRequest (_http_client.js:73:11)
    at TunnelingAgent.exports.request (http.js:49:10)
    at TunnelingAgent.createSocket (.../test/node_modules/cloudant/node_modules/request/node_modules/tunnel-agent/index.js:117:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (.../test/node_modules/cloudant/node_modules/request/node_modules/tunnel-agent/index.js:184:41)
    at TunnelingAgent.addRequest (.../test/node_modules/cloudant/node_modules/request/node_modules/tunnel-agent/index.js:80:8)
    at new ClientRequest (_http_client.js:154:16)
    at Object.exports.request (http.js:49:10)
    at Object.exports.request (https.js:136:15)
```

It looks like it is coming from `request` dependency failing with config parsing. So I've just tried at upgrading this dependency from 2.33.0 to 2.55.0 and then the connection is working on Node.js 0.12.2.

Could you please confirm and make a short status, if possible, on Node.js 0.12.2 support?
And regarding the overall release, the lib is in beta. Any date when it will be considered release?

Thanks.
BR,
Fabrice

**Comment by jhs** [comment]
Thanks! I will merge the latest Nano version and cut a 1.1 release this week. I will let you know when that happens and I would love to hear if it solves the problem. If not, we can keep looking at it.

**Comment by jhs** [comment]
HI, @spifd. Please try the new 1.0.0 release from npm. We have merged in the latest Nano release, including all of its dependencies of course.

In the future, we are moving to make Nano a proper dependency, rather than a fork. This should make your life even easier.

Let me know if you have any problems. Thanks again for reporting your issue!
