### ISSUE TITLE
Check about the changes api

### ISSUE THREAD

**Issue by jhs** [cloudant/nodejs-cloudant#59]
Confirm that it works correctly

**Comment by remkoboschker** [comment]
Hi, 
I just received a strange error message from the follow.js code 

````
 "Error: Database deleted after change: 2404-g1AAAAEneJzLYWBgYMlgTmGQT0lKzi9KdUhJMtHLSs1LLUst0kvOyS9NScwr0ctLLckBKmRKZEiy____f1YGUxIDA-O3XKAYe7JRskGKsTmqGWa4zUhyAJJJ9XBjmBLBxhgYJVkmohuDxyl5LECSoQFIAU3aDzWqFGyUuYlxUnJyMtEughh1AGIUzFUzwEYZmxqkGqYZZQEAGN1ZWg\n    at Feed.on_couch_data (/home/generators/services/node_modules/cloudant/node_modules/follow/lib/feed.js:437:18)\n    at Changes.handle_confirmed_req_event (/home/generators/services/node_modules/cloudant/node_modules/follow/lib/feed.js:322:30)\n    at Changes.emit (events.js:107:17)\n    at Changes.emit_changes (/home/generators/services/node_modules/cloudant/node_modules/follow/lib/stream.js:223:12)\n    at Changes.write_continuous (/home/generators/services/node_modules/cloudant/node_modules/follow/lib/stream.js:176:8)\n    at Changes.write (/home/generators/services/node_modules/cloudant/node_modules/follow/lib/stream.js:124:17)\n    at Request.ondata (stream.js:51:26)\n    at Request.emit (events.js:107:17)\n    at IncomingMessage.<anonymous> (/home/generators/services/node_modules/request/request.js:1150:12)\n    at IncomingMessage.emit (events.js:107:17)\n    at readableAddChunk (_stream_readable.js:163:16)\n    at IncomingMessage.Readable.push (_stream_readable.js:126:10)\n    at HTTPParser.parserOnBody (_http_common.js:132:22)\n    at TLSSocket.socketOnData (_http_client.js:317:20)\n    at TLSSocket.emit (events.js:107:17)\n    at readableAddChunk (_stream_readable.js:163:16)",
````

Luckily the database was not deleted :smiley:

**Comment by jhs** [comment]
Ha ha, sorry, that is very likely my own code that output that. "Printer on fire!"

I think the code detects for 404 or other errors and assumes the database is deleted. That is one way to trigger that code path, but apparently not the only way.

We are working to close this by this coming Tuesday at the latest.

**Comment by jhs** [comment]
@remkoboschker Have you still got this bug in the new 1.1 release? I think you may still have it. If so, we can work more fixes into the Follow and Nano code, which are dependencies of the Cloudant package.

**Comment by remkoboschker** [comment]
@jhs I'll update and keep you informed. I'm not sure how I can reproduce the bug.

**Comment by jhs** [comment]
Hi, @remkoboschker. I will close this ticket for now, since all the tests I can think of are passing. However, I definitely think there is still brittleness in the changes code. However I'll open a fresh ticket about that as I encounter it. Thanks!

**Comment by remkoboschker** [comment]
@jhs thank you. I'll let you know when I observe any strange behaviour.

**Comment by remkoboschker** [comment]
````
{
  "message": "Database deleted after change: 3406-g1AAAAEneJzLYWBgYMlgTmGQT0lKzi9KdUhJstTLSs1LLUst0kvOyS9NScwr0ctLLckBKmRKZEiy____f1YGUxKQ9zkXKMZuapZsmJaYgmqGKW4zkhyAZFI93BjmALAxqYaWKUkpBkQ7JY8FSDI0ACmgSfuhRlWBjTJINEg1SUwl2kUQow5AjIK5aiLYqEQzA3Mzg9QsAHr6Wd8",
  "stack": "Error: Database deleted after change: 3406-g1AAAAEneJzLYWBgYMlgTmGQT0lKzi9KdUhJstTLSs1LLUst0kvOyS9NScwr0ctLLckBKmRKZEiy____f1YGUxKQ9zkXKMZuapZsmJaYgmqGKW4zkhyAZFI93BjmALAxqYaWKUkpBkQ7JY8FSDI0ACmgSfuhRlWBjTJINEg1SUwl2kUQow5AjIK5aiLYqEQzA3Mzg9QsAHr6Wd8\n    at Feed.on_couch_data (/home/generators/services/node_modules/cloudant/node_modules/nano/node_modules/follow/lib/feed.js:440:18)\n    at Changes.handle_confirmed_req_event (/home/generators/services/node_modules/cloudant/node_modules/nano/node_modules/follow/lib/feed.js:325:30)\n    at Changes.emit (events.js:107:17)\n    at Changes.emit_changes (/home/generators/services/node_modules/cloudant/node_modules/nano/node_modules/follow/lib/stream.js:223:12)\n    at Changes.write_continuous (/home/generators/services/node_modules/cloudant/node_modules/nano/node_modules/follow/lib/stream.js:176:8)\n    at Changes.write (/home/generators/services/node_modules/cloudant/node_modules/nano/node_modules/follow/lib/stream.js:124:17)\n    at Request.ondata (stream.js:51:26)\n    at Request.emit (events.js:107:17)\n    at IncomingMessage.<anonymous> (/home/generators/services/node_modules/cloudant/node_modules/nano/node_modules/follow/node_modules/request/request.js:1164:12)\n    at IncomingMessage.emit (events.js:107:17)\n    at readableAddChunk (_stream_readable.js:163:16)\n    at IncomingMessage.Readable.push (_stream_readable.js:126:10)\n    at HTTPParser.parserOnBody (_http_common.js:132:22)\n    at TLSSocket.socketOnData (_http_client.js:317:20)\n    at TLSSocket.emit (events.js:107:17)\n    at readableAddChunk (_stream_readable.js:163:16)",
  "deleted": true,
  "last_seq": "3406-g1AAAAEneJzLYWBgYMlgTmGQT0lKzi9KdUhJstTLSs1LLUst0kvOyS9NScwr0ctLLckBKmRKZEiy____f1YGUxKQ9zkXKMZuapZsmJaYgmqGKW4zkhyAZFI93BjmALAxqYaWKUkpBkQ7JY8FSDI0ACmgSfuhRlWBjTJINEg1SUwl2kUQow5AjIK5aiLYqEQzA3Mzg9QsAHr6Wd8",
  "time": "2015-08-19T14:10:47.105Z",
  "level": "err"
} 
````

I happy to report the database is still there. Also there were no changes at all.

**Comment by remkoboschker** [comment]
again at "2015-09-09T16:41:47.691Z"; does this mean there was a service interuption at cloudant?

**Comment by nicolelovecoding** [comment]
Just received the same error: "Error: Database deleted after change:...."

**Comment by csaroff** [comment]
It seems this issue is percolating up from the follow api.  I've put in an [issue there](https://github.com/iriscouch/follow/issues/78), but I'm not sure if this repository is still being maintained.  In the meantime, anyone who is having this issue can look at the [pouchdb changes api](http://pouchdb.com/guides/changes.html#live-changes-feed) which also appears to extend EventListener.
